steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'
      - '-f'
      - cloud_run/ftp/Dockerfile
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_CLOUD_RUN_SERVICE_NAME}'
      - '--service-account'
      - '${_COMPOSER_SERVICE_ACCOUNT}'
      - '--project'
      - '${_PROJECT_ID}'
      - '--image'
      - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'
      - '--region'
      - '${_LOCATION}'
      - '--memory'
      - '4Gi'
      - '--timeout'
      - '1200'
      - '--cpu'
      - '2'
      - '--no-allow-unauthenticated'
