steps:
  - id: 'Get and Store Composer Bucket Name'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/bash'
    args:
      - -c
      - |
        $(gcloud composer environments describe ${_COMPOSER_NAME} --project ${_PROJECT_ID} --location ${_LOCATION} | grep "dagGcsPrefix" | grep -Eo "\S+/" > /workspace/dagGcsPrefix.txt)


  - id: 'Move Objects to DAG Folder'
    name: 'gcr.io/cloud-builders/gsutil'
    dir: 'composer/dag'
    entrypoint: '/bin/bash'
    args:
      - -c
      - |
        echo "Read Environment Variables"
        echo "**** prefix **"
        echo $(cat /workspace/dagGcsPrefix.txt)
        dag_path=$(cat /workspace/dagGcsPrefix.txt)dags
        echo $dag_path
        $(gsutil -m cp *.py $dag_path)

#  - id: 'Prepare Test Env'
#    name: 'gcr.io/cloud-builders/gsutil'
#    args: [ '-m', 'cp', '-r', 'gs://dec-cam-ftp-d-us-east4-ingestion-b3b3/uploads/', 'gs://dec-cam-ftp-d-us-east4-ingestion-b3b3/dev_test_uploads/' ]
#    waitFor: [ '-' ]  # The '-' indicates that this step begins immediately.
