SELECT
  id,
  address,
  beds,
  city,
  country,
  county,
  countyfips,
  excess_bed as excess_beds,
  latitude,
  longitude,
  medicaidid as medicaid_id,
  medicareid as medicare_id,
  naics_code,
  naics_desc,
  name,
  objectid as object_id,
  ownership as owneship,
  population,
  source,
  sourcedate as source_date,
  sourcetype as source_type,
  state,
  state_lic,
  status,
  telephone,
  tot_res,
  tot_staff,
  type,
  val_date,
  val_method,
  website,
  zip,
  zip4,
  geo_metadata,
  ST_GeogPoint(longitude, latitude) AS geometry,
  record_date,
  ingestion_timestamp
FROM
  `warehouse.arcgis_nursing_homes`