SELECT
  CAST(site AS STRING) AS site,
  data_status,
  action_code,
  datetime,
  parameter,
  duration,
  frequency,
  CAST(value AS NUMERIC) AS value,
  unit,
  qc,
  poc,
  latitude,
  longitude,
  ST_GeogPoint(longitude, latitude) AS geometry,
  gisdatum,
  elev,
  CAST(method_code AS STRING) AS method_code,
  mpc,
  CAST(mpc_value AS NUMERIC) AS mpc_value,
  CAST(uncertainty AS NUMERIC) AS uncertainty,
  qualifiers,
  PARSE_DATE("%Y%m%d", REGEXP_SUBSTR(datetime, "(.*)T")) AS date,
  CONCAT(SUBSTRING(REGEXP_SUBSTR(REGEXP_SUBSTR(datetime, "(.*)-"), "T(.*)"), 1, 2), ':00') AS time_local,
  CONCAT(SUBSTRING(REGEXP_SUBSTR(datetime, "-(.*)"), 1, 2), ':00') AS time_gmt,
  PARSE_DATE("%Y%m%d", REGEXP_SUBSTR(datetime, "(.*)T")) AS record_date,
  ingestion_timestamp,
  file_name,
FROM
  `warehouse.ftp_airnow_i`