SELECT
  facility_name,
  CAST(decid AS STRING) AS decid,
  CAST(oris_id AS STRING) AS oris_id,
  address,
  city,
  state,
  CAST(zip AS STRING) AS zip,
  latitude,
  longitude,
  ST_GeogPoint(longitude, latitude) AS geo_point,
  nytme_coordinate,
  nytmn_coordinate,
  voc_tons,
  nox_tons,
  co_tons,
  co2_tons,
  particulates_tons,
  pm10_tons,
  pm2_5_tons,
  haps_tons,
  so2_tons,
  record_date,
  ingestion_timestamp
FROM
  `ingestion.power_generation_facilities_facility`