SELECT
  address,
  certificate_number,
  city,
  classification,
  county,
  facility_id,
  facility_name,
  fax,
  number_of_beds,
  operator,
  phone,
  regional_office,
  type,
  zip,
  assisted_living_program_beds,
  assisted_living_residence_alr_beds,
  enhanced_alr_beds,
  STRUCT( STRUCT(geo_metadata.human_address.address,
      geo_metadata.human_address.city,
      geo_metadata.human_address.state,
      geo_metadata.human_address.zip) AS human_address,
    CAST(geo_metadata.latitude AS FLOAT64) AS latitude,
    CAST(geo_metadata.longitude AS FLOAT64) AS longitude,
    geo_metadata.needs_recoding) AS geo_metadata,
  ST_GeogPoint(CAST(geo_metadata.longitude AS FLOAT64),
    CAST(geo_metadata.latitude AS FLOAT64)) AS geometry,
  special_needs_alr_beds,
  record_date,
  ingestion_timestamp
FROM
  `warehouse.socrata_adult_care_facility_map`