SELECT
  address1,
  city,
  cnty_cd,
  computed_region_43an_4dx5,
  computed_region_5edz_4hdv,
  computed_region_9yqb_tdyd,
  computed_region_assa_msit,
  cooperator_state,
  county,
  description,
  fac_desc_short,
  fac_id,
  fac_opn_dat,
  fac_phone,
  fac_zip,
  STRUCT(CAST(geo_metadata.longitude AS FLOAT64) AS longitude,
    CAST(geo_metadata.latitude AS FLOAT64) AS latitude,
    geo_metadata.needs_recoding) AS geo_metadata,
  facility_name,
  CAST(latitude AS FLOAT64) AS latitude,
  CAST(longitude AS FLOAT64) AS longitude,
  ST_GeogPoint(CAST(longitude AS FLOAT64),
    CAST(latitude AS FLOAT64)) AS geometry,
  opcert_num,
  operator_address1,
  operator_city,
  operator_name,
  operator_state,
  operator_zip,
  region_office,
  ro_id,
  state,
  fac_fax,
  computed_region_8ire_itmf,
  operator_address2,
  main_site_facid,
  main_site_name,
  web_site,
  address2,
  cooperator_address1,
  cooperator_city,
  cooperator_name,
  cooperator_zip,
  cooperator_address2,
  record_date,
  ingestion_timestamp
FROM
  `warehouse.socrata_health_facility_map`