SELECT
  additional_information,
  address_omitted,
  capacity_description,
  city,
  county,
  facility_id,
  facility_name,
  facility_opened_date,
  facility_status,
  infant_capacity,
  license_expiration_date,
  license_issue_date,
  phone_number,
  preschool_capacity,
  program_type,
  provider_name,
  region_code,
  school_age_capacity,
  school_district_name,
  state,
  toddler_capacity,
  total_capacity,
  zip_code,
  additional_address,
  phone_extension,
  street_name,
  street_number,
  computed_region_kjdx_g34t,
  computed_region_wbg7_3whc,
  computed_region_yamh_8v7k,
  geo_metadata,
  CAST(latitude AS FLOAT64) AS latitude,
  CAST(longitude AS FLOAT64) AS longitude,
  ST_GeogPoint(CAST(longitude AS FLOAT64),
    CAST(latitude AS FLOAT64)) AS geometry,
  apartment,
  floor,
  phone_number_omitted,
  CAST(record_date AS DATE) AS record_date,
  ingestion_timestamp
FROM
  `warehouse.socrata_child_care_regulated_programs`